### ISSUE TITLE
Provide a way to test groups of packages in version jumps

### ISSUE THREAD

**Issue by Graham42** [watson/test-all-versions#1]
Use case: I want to test against `react-dom` 0.14 or 15.x which requires a peer dependency of `react`. However the version that is needed is always in sync. This will be true for any large package group managed with https://lernajs.io/

Something like this currently doesn't work

```yaml
react-dom:
  peerDependencies: react
  versions: 0.14.x || 15.3.x
  commands: npm run test
```

Wondering if you could extend the config to allow a structure that can specify any number of packages. And then run the tests upgrading those packages in sync.

Example:
```yaml
react-test-1:
  packages:
    - react
    - react-dom
  versions: 0.14.x || 15.3.x
  commands: npm run test
```

Thoughts?
