### ISSUE TITLE
[QUESTION] How to access to test env variables

### ISSUE THREAD

**Issue by arredgroup** [watson/test-all-versions#24]
Hi! Do you know if exists any way to get in test file the current version via environment variables or similar? maybe passing the data in the yml file?? for example:
`'@odizy/o11y-ia-agent':
  versions: "^1.1.5"
  node: '>=20.0.0'
  env:
    - version=$TAV.version
  commands:
    - jest global.spec.js --runInBand --config=jest.config.js
`

**Comment by watson** [comment]
Not directly, but if you use the `pretest` yaml property you can run any shell script you like to read the version from the installed `package.json`, e.g:

```yaml
graphql:
  versions: ^0.7.0
  pretest: export version=$(node -p "require('graphql/package.json').version")
  commands: node test/graphql.js
```

(I'm writing this from memory, so maybe the exact pretest command might need to be modified slightly)
